coverage:
  range: 70..90
  status:
    patch: false
fixes:
  - "/home/runner/work/gpjax/gpjax/::" # Correct paths

ignore:
  - "gpjax/_version.py"
  - "*.py"
  - "tests/*.py"
  - "test_*.py"
  - "*_version.py"
  - "versioneer.py"
