name: Build the documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build docs (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: create Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.9

      - name: Build the documentation with Sphinx
        run: |
          pip install -r docs/requirements.txt
          conda install pandoc
          cd docs
          make html
