#name: Run Python Tests
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Python 3
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.6
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#          python setup.py install
#          pip install pytest==6.1.2
#      - name: Run tests with pytest
#        run: pytest ./tests
#      - name: Upload results
#        run: bash <(curl -s https://codecov.io/bash) -t "${{ secrets.CODECOV_TOKEN }}"


name: Run unit tests
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py install
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml ./tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true